server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 是否注册进eureka
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。集群时必须设置
    fetch-registry: true
    service-url:
      # defaultZone: http://127.0.0.1:7001/eureka
      # 集群版
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    # 实例名
    instance-id: order80
    # 显示IP地址
    prefer-ip-address: true