server:
  port: 8769

spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      # defaultZone: http://127.0.0.1:7001/eureka
      # 集群版
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
zuul:
  # host:
    # HTTP连接超时时间, 必须大于Hystrix的超时时间, 否则会报错
    # connect-timeout-millis: 15000
    # Socket超时时间
    # socket-timeout-millis: 60000
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign

# 设置ribbon的超时时间小于zuul的超时时间
# ribbon:
  # ReadTimeout: 10000
  # ConnectTimeout: 10000
