server:
  port: 8764

spring:
  application:
    name: service-ribbon

eureka:
  client:
    service-url:
      # defaultZone: http://127.0.0.1:7001/eureka
      # 集群版
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka